### ISSUE TITLE
Add optional config to save all outputs

### ISSUE THREAD

**Issue by jenreiter** [flywheel-apps/mriqc#14]
Currently, mriqc only outputs the summary html report. Add a configuration that will save all generated outputs from the algorithm. 

_config info_
name: 'save_outputs'
type: 'boolean'
default: off

TODO: Determine if functionality can be added to make gear run as a utility gear or an analysis gear.

**Comment by jenreiter** [comment]
@lmperry I am going to start implementing this feature as described. Let me know if you want me to wait on it...

**Comment by jenreiter** [comment]
@lmperry Almost done with this. Only one more question on implementation. Should the file "type" of the zipfile be "qa" (same as the .qa.html file) or should it be "archive" since it's a zip file.

**Comment by lmperry** [comment]
Good question: It's both - I'd go with `qa` as it's more informative - and hope the UI does not try to render it.

**Comment by jenreiter** [comment]
Ok, sounds good. Here's an example acquisition, 'ep2d_neuro_PA_Rest_3mm', of the output with type 'qa'.

https://dev.flywheel.io/#/dashboard/project/59c59b438a3e550019dfc7ab/session/59cc0140547165f79231a413?tab=data
