### ISSUE TITLE
docs link in output is broken

### ISSUE THREAD

**Issue by tcbtcb** [flywheel-apps/mriqc#24]
+++
I opened one of the QC documents and at the very bottom, you have the link to a user guide 
http://mriqc.readthedocs.io/en/latest/userguide.html

Looks like the link is broken. There is no documentation in this link. 
Just wanted to let you know. 
+++
confirmed. link should be 

http://mriqc.readthedocs.io/en/latest/

**Comment by lmperry** [comment]
That is generated by the MRIQC algo, not the gear. It should be addressed by a MRQC algo upgrade. I will try to remember to close this when I upgrade that, unless your happy closing now.
