### ISSUE TITLE
Measurement/classification of resultant html file is incorrect

### ISSUE THREAD

**Issue by jenreiter** [flywheel-apps/mriqc#6]
Currently the measurement/classification of the output html file is "T1w". 
The correct measurement/classification value of a structural T1w image is "Anatomy_t1w". 

See screenshot below:
<img width="775" alt="screen shot 2017-09-19 at 9 10 50 am 2" src="https://user-images.githubusercontent.com/23246796/30597237-0a6141b0-9d1c-11e7-9408-f5b9bf99d2d3.png">

However, since this is an html report and not an actual T1w image, I believe this should not be used. 
@lmperry do you have thoughts on what the measurement/classification should be for the MRIQC output html file?

**Comment by lmperry** [comment]
In this case the classification should be inherited from the source data, which will be [Structural, T1].

See https://github.com/scitran/core/issues/402
